version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./Functions_triggers.sql:/docker-entrypoint-initdb.d/Functions_triggers.sql
      - ./Tables.sql:/docker-entrypoint-initdb.d/Tables.sql
      - app-data:/tmp:z

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "10000:10000"
    volumes:
      - app-data:/tmp:z

volumes:
  data:
  app-data:
